// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHAsMyOhUd_DfwfCOaqWGPD1X-XfoH8RI',
    appId: '1:922418710491:web:1eb46249b7ce42ebd589fe',
    messagingSenderId: '922418710491',
    projectId: 'login-9dc05',
    authDomain: 'login-9dc05.firebaseapp.com',
    storageBucket: 'login-9dc05.appspot.com',
    measurementId: 'G-N58QB5QJM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALsfS65es5_MbSyDIuhnNzZTstUWo_GbQ',
    appId: '1:922418710491:android:066efc69278e91a2d589fe',
    messagingSenderId: '922418710491',
    projectId: 'login-9dc05',
    storageBucket: 'login-9dc05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX3VIG0vshvgwP7Exhfh1OHTDY4u9uP8w',
    appId: '1:922418710491:ios:35006dfa15af9f1dd589fe',
    messagingSenderId: '922418710491',
    projectId: 'login-9dc05',
    storageBucket: 'login-9dc05.appspot.com',
    androidClientId: '922418710491-7tqvgh40cv8t9kkg5kgabm048a52069l.apps.googleusercontent.com',
    iosClientId: '922418710491-1sbe4i3t0p44g37aeahcfn3o278jcsht.apps.googleusercontent.com',
    iosBundleId: 'com.example.test4Login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX3VIG0vshvgwP7Exhfh1OHTDY4u9uP8w',
    appId: '1:922418710491:ios:35006dfa15af9f1dd589fe',
    messagingSenderId: '922418710491',
    projectId: 'login-9dc05',
    storageBucket: 'login-9dc05.appspot.com',
    androidClientId: '922418710491-7tqvgh40cv8t9kkg5kgabm048a52069l.apps.googleusercontent.com',
    iosClientId: '922418710491-1sbe4i3t0p44g37aeahcfn3o278jcsht.apps.googleusercontent.com',
    iosBundleId: 'com.example.test4Login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHAsMyOhUd_DfwfCOaqWGPD1X-XfoH8RI',
    appId: '1:922418710491:web:688c41e865b999e5d589fe',
    messagingSenderId: '922418710491',
    projectId: 'login-9dc05',
    authDomain: 'login-9dc05.firebaseapp.com',
    storageBucket: 'login-9dc05.appspot.com',
    measurementId: 'G-2NRR1YG88Q',
  );
}
